---
title: "People"
---

## About Me

I am an associate professor of geology and science education, and a member of both the Geology Department and the SMATE (Science, Math and Technology Education) Group at Western Washington University. I earned both my PhD and MS in Earth Science at the University of Riverside, CA and my BA in Geology at Oberlin College.

My professional training is in marine paleoecology, with a focus on Ordovician gastropod evolution, but I have also developed a research program in geoscience education, with a focus on equity and justice in geoscience.

## Current Members

-   Mattie Horne
    -   Thesis: *Using exploration-based activities and 3D-modeled fossils as tools to introduce geoscience concepts in the classroom*

## Past Members

-   Willa Rowan (WWU M.S. 2023)

    -   Thesis: *A mixed-methods study of geoscience identity, race/ethnicity, and gender in senior undergraduate geoscience majors* ([read on CEDAR](https://cedar.wwu.edu/wwuet/1237/))

-   Eston Worthington (WWU M.S. 2021)

    -   Thesis: *Reevaluating the use of mollusks for estimating paleodepth in the Pacific Northwest* ([read on CEDAR](https://cedar.wwu.edu/wwuet/1051/))

-   Alex Hernandez (WWU M.S. 2021)

    -   Thesis: *Marine ecosystem response to Late Plesitocene rapid climate change in the Salish Sea* ([read on CEDAR](https://cedar.wwu.edu/wwuet/1014/))

    -   Currently: completing his doctorate at the University of Bremen
