---
title: "Teaching"
---

## Courses for Fall 2025

SCED 201: Matter & Energy in Physical Systems

## Current Office Hours

Mondays 2-3pm

Wednesdays 1-3pm

or by appointment

## WWU Courses Regularly Taught

<details>

<summary>GEOL 212: Historical Geology</summary>

Evolution of the major features of the earth's surface and of life; history of the ocean basins, continents and mountain belts related to the theory of plate tectonics; geologic history of North America and the Pacific Northwest.

</details>

<details>

<summary>GEOL 316: Paleontology</summary>

This course is an introduction to the study of paleontology, covering topics including the history of life on Earth, evolutionary theory and speciation, extinction and recovery, systematics and fossil classification, modes of fossilization, and the nature and completeness of the fossil record.

</details>

<details>

<summary>SCED 201: Matter & Energy in Physical Systems</summary>

This course is the first in a 4 course series designed for prospective elementary teachers but open to all students. The course uses a student-oriented pedagogy with an integrated content focus to help students develop important ideas in physical science.

</details>

<details>

<summary>SCED 202: Matter & Energy in the Earth System</summary>

This course is one of a 4 course series designed for prospective elementary teachers but open to all students. The course uses a student-oriented pedagogy with an integrated content focus to help students develop important ideas in earth science.

</details>

<details>

<summary>SCED 370: STEM & Society</summary>

In this course, we will explore the meaning and importance of scientific literacy and consider how scientific literacy relates to issues of equity and social justice. We will discuss different types of scientific controversy, study how scientific research is portrayed in news and popular media, and examine frameworks for teaching scientific literacy at the secondary level.

</details>

## Teaching History

+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| Year         | Winter                              | Spring                              | Fall                                |
+==============+=====================================+=====================================+=====================================+
| 2026         | Matter & Energy in the Earth System | Matter & Energy in Physical Systems |                                     |
|              |                                     |                                     |                                     |
|              | Paleontology                        | Historical Geology                  |                                     |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2025         | Historical Geology                  | Historical Geology                  | Matter & Energy in Physical Systems |
|              |                                     |                                     |                                     |
|              |                                     | STEM & Society                      |                                     |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2024         | Historical Geology                  | *parental leave*                    | Paleontology                        |
|              |                                     |                                     |                                     |
|              | Matter & Energy in the Earth System |                                     | STEM & Society                      |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2023         | Paleontology                        | Historical Geology                  | STEM & Society                      |
|              |                                     |                                     |                                     |
|              |                                     | Matter & Energy in the Earth System |                                     |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2022         | *parental leave*                    | *parental leave*                    | Historical Geology                  |
|              |                                     |                                     |                                     |
|              |                                     |                                     | STEM & Society                      |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2021         | Paleontology                        | Paleontology                        | Advanced Paleobiology               |
|              |                                     |                                     |                                     |
|              | Matter & Energy in the Earth System | STEM & Society                      | STEM & Society                      |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2020         | Matter & Energy in Physical Systems | Paleontology                        | Paleontology                        |
|              |                                     |                                     |                                     |
|              |                                     | Matter & Energy in the Earth System |                                     |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2019         | Advanced Paleobiology               | Historical Geology                  | Historical Geology                  |
|              |                                     |                                     |                                     |
|              | Matter & Energy in the Earth System | Matter & Energy in the Earth System |                                     |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2018         | Matter & Energy in Physical Systems | Historical Geology                  | Paleontology                        |
|              |                                     |                                     |                                     |
|              |                                     | Matter & Energy in Physical Systems |                                     |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
| 2017         | Earth Materials                     | Earth Materials                     | Earth Materials                     |
|              |                                     |                                     |                                     |
|              |                                     | Matter & Energy in the Earth System | Matter & Energy in the Earth System |
+--------------+-------------------------------------+-------------------------------------+-------------------------------------+
